### ISSUE TITLE
Recognize release key 394271

### ISSUE THREAD

**Issue by atifaziz** [shanselman/SmallestDotNet#65] opened 2016-01-08 14:36 UTC
Running `CheckForDotNet45.exe` on a box with .NET 4.6 installed took me to http://smallestdotnet.com/?releaseKey=394271 and where I was told I should log an issue:

> Please log an issue including this information: releaseKey=394271 so we can get it exact in the future. 

So here I am.

In case it helps, the machine has **Microsoft Windows NT 6.1.7601 Service Pack 1** (64-bit version) installed.

**Comment by tohidazizi** [comment] 2016-01-22 15:19
Same on my machine:

> We Found .NET!
> The .Net Checker application determined that you have 4.6 or greater on your machine. The application was not able to determine the exact version you have. Please log an issue including this information: releaseKey=394271 so we can get it exact in the future.

**Comment by gkara** [comment] 2016-01-25 08:52
Same here.

**Comment by rudelafuente** [comment] 2016-01-26 13:37
I got the same error and have version 4.6.1 of the .NET Framework on a Windows 7 machine.

**Comment by shanselman** [comment] 2016-03-01 06:26
Dupe of #66

**Closed by shanselman** 2016-03-01 06:26 UTC
Labels: bug, first-timers-only
