### ISSUE TITLE
 releaseKey=460798 

### ISSUE THREAD

**Issue by HidayathAman** [shanselman/SmallestDotNet#91] opened 2018-01-03 20:52 UTC
When I run the dotnetchecker , I get the following message from IE (The .Net Checker application determined that you have 4.6.2 or greater on your machine. The application was not able to determine the exact version you have, Please log an issue including this information: releaseKey=460798 so we can get it exact in the future. ) so logging it here , don't know if you need any additional details

**Comment by binki** [comment] 2018-01-26 19:56
From https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed#net_b

> On Windows 10 Creators Update: 460798 On all other OS versions: 460805 | .NET Framework 4.7
-- | --

( as in .net-4.7.0 though MS calls it 4.7)

**Comment by binki** [comment] 2018-01-26 19:59
This is a duplicate of #88

**Closed** 2018-10-10 05:11 UTC
