### ISSUE TITLE
releaseKey=460798 

### ISSUE THREAD

**Issue by damnnutnow** [shanselman/SmallestDotNet#88] opened 2017-08-23 03:19 UTC
We Found .NET!

The .Net Checker application determined that you have 4.6.2 or greater on your machine. The application was not able to determine the exact version you have. Please log an issue including this information: releaseKey=460798 so we can get it exact in the future.

**Comment by embix** [comment] 2017-08-28 13:28
Same releaseKey here. Windows 10, 1703 with .NET Framework 4.7 which matches [MSDN Docu](https://docs.microsoft.com/en-us/dotnet/framework/migration-guide/how-to-determine-which-versions-are-installed)

**Comment by embix** [comment] 2017-08-28 13:30
duplicate of #83

**Closed** 2018-10-10 05:11 UTC
